# Generated by Django 5.2 on 2025-04-10 10:50

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_sketch_created_by_book_sketch_book"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="sketch",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="book",
            name="title",
        ),
        migrations.AddField(
            model_name="book",
            name="name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sketch",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="collaborating_books", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_books",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sketch",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.book"
            ),
        ),
        migrations.AlterField(
            model_name="sketch",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="UserColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(default=app.models.random_color, max_length=7),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("book", "user")},
            },
        ),
    ]
